server:
  port: ${AUTH_PORT}

spring:
  application:
    name: ${AUTH_HOST}
  cloud:
    config:
      enabled: false

  # === database ===
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 30
      connection-timeout: 30000       # 커넥션 요청 최대 대기 시간 (ms)
      validation-timeout: 5000        # 커넥션 유효성 검사 타임아웃 (ms)
      idle-timeout: 300000            # 유휴 커넥션 유지 시간 (ms)
      max-lifetime: 1800000           # 커넥션 최대 수명 (ms)
      leak-detection-threshold: 2000  # 2초 이상 반납 안 하면 로그 경고
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
  instance:
    preferIpAddress: true
    hostname: ${spring.application.name}
    instanceId: ${spring.application.name}:${server.port}
    metadataMap:
      management.port: ${management.server.port}

logging:
  level:
    root: WARN
    com.genieus: INFO
    shop.genieus: INFO
  config: classpath:logback-dev.xml

management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v2/spans
  server:
    port: ${MANAGEMENT_AUTH_PORT}
  endpoints:
    web:
      exposure:
        include: health,prometheus
  tracing:
    sampling:
      probability: 0.01
    web:
      exclude-patterns:
        - "/actuator/**"
        - "/prometheus"
        - "/eureka/**"
jwt:
  secret: ${JWT_SECRET}
