spring:
  application:
    name: ${EUREKA_HOST}

server:
  port: ${EUREKA_PORT}
  servlet:
    context-path: /eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,prometheus

security:
  user:
    name: ${EUREKA_USERNAME}
    password: ${EUREKA_PASSWORD}

logging:
  level:
    root: info
    com.netflix.discovery: info # Eureka 클라이언트 로깅
    com.netflix.eureka: info # Eureka 서버 자체 로깅
    org.springframework.cloud.netflix.eureka: debug # Spring Cloud Netflix Eureka Wrapper
    # 필요할 경우만 trace
    # com.netflix.discovery: trace