spring:
  application:
    name: ${EUREKA_HOST}

server:
  port: ${EUREKA_PORT}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v2/spans
  tracing:
    enabled: false
    sampling:
      probability: 0.01
  endpoints:
    web:
      exposure:
        include: health,prometheus

security:
  user:
    name: ${EUREKA_USERNAME}
    password: ${EUREKA_PASSWORD}

logging:
  level:
    root: WARN
    shop.genieus: INFO
  config: classpath:logback-dev.xml
