server:
  port: ${EUREKA_PORT}
management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health

eureka:
  server:
    enable-self-preservation: true

security:
  user:
    name: ${EUREKA_USERNAME}
    password: ${EUREKA_PASSWORD}

logging:
  level:
    root: info
    com.netflix.discovery: debug # Eureka 클라이언트 디버깅 (등록/갱신 확인)
    com.netflix.eureka: debug # Eureka 서버 디버깅 (인스턴스 상태 추적)
    org.springframework.cloud.netflix.eureka: debug # Spring Cloud Eureka 설정 디버깅
    # 필요할 경우만 trace (예: 등록 누락 등 이슈 추적 시 사용)
    # com.netflix.discovery: trace
