# 웹 서버를 아예 띄우지 않음
server:
  port: -1
spring:
  cloud:
    discovery:
      enabled: false
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 300000       # 5분
      max-lifetime: 3600000      # 1시간
      leak-detection-threshold: 2000
      connection-test-query: SELECT 1
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  autoconfigure:
    exclude:
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
      - org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClientAutoConfiguration

# Zipkin 비활성화
management:
  tracing:
    enabled: false

logging:
  level:
    root: info
    shop.genieus: debug
    org.springframework.cloud.gateway: debug
    org.springframework.web.reactive: info
    reactor.netty: warn
