eureka:
  client:
    serviceUrl:
      defaultZone: http://username:password@localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: ${spring.application.name}
    instanceId: ${spring.application.name}:${server.port}

spring:
  config:
    activate:
      on-profile: batch-dev
    import: 'classpath:docker-database.yml'

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

# 웹 서버를 아예 띄우지 않음
server:
  port: -1
