spring:
  config:
    activate:
      on-profile: batch-dev
    import: 'classpath:docker-database.yml'

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

# 웹 서버를 아예 띄우지 않음
server:
  port: -1
