# 웹 서버를 아예 띄우지 않음
server:
  port: -1
spring:
  cloud:
    discovery:
      enabled: false
  batch:
    job:
      enabled: false # 자동 job 실행 비활성화
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3307/genieus
    username: root
    password: 1234
  data:
    redis:
      host: host.docker.internal
      port: 6379