INSERT INTO m_promotion (promotion_id,
                         promotion_name,
                         promotion_start_date,
                         promotion_end_date,
                         promotion_status,
                         created_at,
                         updated_at,
                         created_by)
VALUES (1,
        '상시 판매',
        STR_TO_DATE('2025-04-10T00:00:00', '%Y-%m-%dT%H:%i:%s'),
        STR_TO_DATE('2026-04-10T23:59:59', '%Y-%m-%dT%H:%i:%s'),
        'ON_PROMOTION',
        NOW(),
        NOW(),
        -1);

INSERT INTO m_promotion_product (product_id,
                                 promotion_product_discount_rate,
                                 promotion_product_status,
                                 promotion_id,
                                 created_at,
                                 updated_at,
                                 created_by)
VALUES (1, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (2, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (3, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (4, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (5, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (6, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (7, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (8, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (9, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (10, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (11, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (12, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (13, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (14, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (15, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (16, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (17, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (18, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (19, 0, 'ON_SALE', 1, NOW(), NOW(), -1),
       (20, 0, 'ON_SALE', 1, NOW(), NOW(), -1);


INSERT INTO m_promotion (promotion_id,
                         promotion_name,
                         promotion_start_date,
                         promotion_end_date,
                         promotion_status,
                         created_at,
                         updated_at,
                         created_by)
VALUES (2,
        '봄맞이 할인 이벤트',
        STR_TO_DATE('2025-04-10T00:00:00', '%Y-%m-%dT%H:%i:%s'),
        STR_TO_DATE('2025-05-30T23:59:59', '%Y-%m-%dT%H:%i:%s'),
        'READY',
        NOW(),
        NOW(),
        -1);

INSERT INTO m_promotion_product (product_id,
                                 promotion_product_discount_rate,
                                 promotion_product_status,
                                 promotion_id,
                                 created_at,
                                 updated_at,
                                 created_by)
VALUES (2, 20, 'READY', 2, NOW(), NOW(), -1),
       (3, 20, 'READY', 2, NOW(), NOW(), -1),
       (4, 20, 'READY', 2, NOW(), NOW(), -1),
       (5, 30, 'READY', 2, NOW(), NOW(), -1),
       (6, 20, 'READY', 2, NOW(), NOW(), -1),
       (7, 20, 'READY', 2, NOW(), NOW(), -1),
       (8, 30, 'READY', 2, NOW(), NOW(), -1),
       (9, 25, 'READY', 2, NOW(), NOW(), -1),
       (10, 20, 'READY', 2, NOW(), NOW(), -1),
       (11, 25, 'READY', 2, NOW(), NOW(), -1),
       (12, 30, 'READY', 2, NOW(), NOW(), -1),
       (13, 40, 'READY', 2, NOW(), NOW(), -1),
       (14, 50, 'READY', 2, NOW(), NOW(), -1),
       (15, 60, 'READY', 2, NOW(), NOW(), -1),
       (16, 25, 'READY', 2, NOW(), NOW(), -1),
       (17, 30, 'READY', 2, NOW(), NOW(), -1),
       (18, 20, 'READY', 2, NOW(), NOW(), -1),
       (19, 40, 'READY', 2, NOW(), NOW(), -1),
       (20, 30, 'READY', 2, NOW(), NOW(), -1);

INSERT INTO m_promotion (promotion_id,
                         promotion_name,
                         promotion_start_date,
                         promotion_end_date,
                         promotion_status,
                         created_at,
                         updated_at,
                         created_by)
VALUES (3,
        '여름 할인 이벤트',
        STR_TO_DATE('2025-04-10T00:00:00', '%Y-%m-%dT%H:%i:%s'),
        STR_TO_DATE('2025-06-20T23:59:59', '%Y-%m-%dT%H:%i:%s'),
        'READY',
        NOW(),
        NOW(),
        -1);

INSERT INTO m_promotion_product (product_id,
                                 promotion_product_discount_rate,
                                 promotion_product_status,
                                 promotion_id,
                                 created_at,
                                 updated_at,
                                 created_by)
VALUES (2, 10, 'READY', 3, NOW(), NOW(), -1),
       (3, 10, 'READY', 3, NOW(), NOW(), -1),
       (4, 10, 'READY', 3, NOW(), NOW(), -1),
       (5, 50, 'READY', 3, NOW(), NOW(), -1),
       (6, 10, 'READY', 3, NOW(), NOW(), -1),
       (7, 10, 'READY', 3, NOW(), NOW(), -1),
       (8, 10, 'READY', 3, NOW(), NOW(), -1),
       (9, 10, 'READY', 3, NOW(), NOW(), -1),
       (10, 10, 'READY', 3, NOW(), NOW(), -1),
       (11, 10, 'READY', 3, NOW(), NOW(), -1),
       (12, 10, 'READY', 3, NOW(), NOW(), -1),
       (13, 10, 'READY', 3, NOW(), NOW(), -1),
       (14, 10, 'READY', 3, NOW(), NOW(), -1),
       (15, 10, 'READY', 3, NOW(), NOW(), -1),
       (16, 10, 'READY', 3, NOW(), NOW(), -1),
       (17, 10, 'READY', 3, NOW(), NOW(), -1),
       (18, 15, 'READY', 3, NOW(), NOW(), -1),
       (19, 10, 'READY', 3, NOW(), NOW(), -1),
       (20, 10, 'READY', 3, NOW(), NOW(), -1);
