eureka:
  client:
    serviceUrl:
      defaultZone: http://username:password@localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: ${spring.application.name}
    instanceId: ${spring.application.name}:${server.port}
    metadataMap:
      management.port: ${management.server.port}
spring:
  cloud:
    config:
      enabled: false
    circuitbreaker:
      resilience4j:
        enabled: true
  config:
    import: 'classpath:docker-database.yml'
  kafka:
    bootstrap-servers: localhost:19092,localhost:19093
    template:
      default-topic: order-events
    consumer:
      group-id: order-service
      topic:
        payment: payment-events
        order: order-events
logging:
  level:
    root: warn
    com.genieus: debug
    shop.genieus: debug

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  server:
    port: 10021
  endpoints:
    web:
      exposure:
        include: health,prometheus

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        record-exceptions:
          - java.io.IOException
          - feign.RetryableException
          - feign.FeignException.FeignServerException
        ignore-exceptions:
          - shop.genieus.order.global.exception.CustomNotFoundException
          - feign.FeignException.FeignClientException
    instances:
      productServiceClient:
        base-config: default
      promotionServiceClient:
        base-config: default
      paymentServiceClient:
        base-config: default
      couponServiceClient:
        base-config: default

order:
  policy:
    order-expiry-seconds: 60
    order-grace-period-seconds: 10
  scheduler:
    poll-interval: 30000