server:
  port: ${ORDER_PORT}

spring:
  application:
    name: ${ORDER_HOST}
  cloud:
    config:
      enabled: false
    circuitbreaker:
      resilience4j:
        enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    template:
      default-topic: order-events
    consumer:
      group-id: order-service
      topic:
        payment: payment-events
        order: order-events

  # === database ===
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 4
      connection-timeout: 30000       # 커넥션 요청 최대 대기 시간 (ms)
      validation-timeout: 5000        # 커넥션 유효성 검사 타임아웃 (ms)
      idle-timeout: 300000            # 유휴 커넥션 유지 시간 (ms)
      max-lifetime: 1800000           # 커넥션 최대 수명 (ms)
      leak-detection-threshold: 2000  # 2초 이상 반납 안 하면 로그 경고
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_updates: true
        batch_versioned_data: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
  instance:
    preferIpAddress: true
    hostname: ${spring.application.name}
    instanceId: ${spring.application.name}:${server.port}
    metadataMap:
      management.port: ${management.server.port}

logging:
  level:
    root: WARN
    com.genieus: DEBUG
    shop.genieus: DEBUG
  config: classpath:logback-dev.xml

management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  server:
    port: ${MANAGEMENT_ORDER_PORT}
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - info

### 커스텀
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        record-exceptions:
          - java.io.IOException
          - feign.RetryableException
          - feign.FeignException.FeignServerException
        ignore-exceptions:
          - shop.genieus.order.global.exception.CustomNotFoundException
          - feign.FeignException.FeignClientException
    instances:
      productServiceClient:
        base-config: default
      promotionServiceClient:
        base-config: default
      paymentServiceClient:
        base-config: default
      couponServiceClient:
        base-config: default

order:
  policy:
    order-expiry-seconds: 120
    order-grace-period-seconds: 10
  scheduler:
    poll-interval: 60000